{
  "Name": "Job_ShouldBeAbleToRunJobWithSpecifiedStepNumber",
  "WorkerConfs": {
    "TestWorker": {
      "WorkerTypeName": "Bam.Net.Automation.Tests.JobManagerUnitTests+TestWorker, bam.net.automation.core.tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "StepNumber": 0,
      "Name": "TestWorker",
      "Properties": {
        "RequiredProperties": "[]"
      }
    },
    "StepTestWorker": {
      "WorkerTypeName": "Bam.Net.Automation.Tests.JobManagerUnitTests+StepTestWorker, bam.net.automation.core.tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "StepNumber": 1,
      "Name": "StepTestWorker",
      "Properties": {
        "RequiredProperties": "[]"
      }
    }
  },
  "WorkerFiles": [
    "/Users/bapellanes/src/BamFrameworkCore/Bam.Net/_tests/core/bam.net.automation.core.tests/TestData/JobManagerService_ShouldBeAbleToRunJobWithSpecifiedStepNumber/Job_ShouldBeAbleToRunJobWithSpecifiedStepNumber/TestWorker.yaml",
    "/Users/bapellanes/src/BamFrameworkCore/Bam.Net/_tests/core/bam.net.automation.core.tests/TestData/JobManagerService_ShouldBeAbleToRunJobWithSpecifiedStepNumber/Job_ShouldBeAbleToRunJobWithSpecifiedStepNumber/StepTestWorker.yaml"
  ],
  "JobDirectory": "/Users/bapellanes/src/BamFrameworkCore/Bam.Net/_tests/core/bam.net.automation.core.tests/TestData/JobManagerService_ShouldBeAbleToRunJobWithSpecifiedStepNumber/Job_ShouldBeAbleToRunJobWithSpecifiedStepNumber"
}