{
  "Name": "Job_AfterAddWorkerCreateJobShouldHaveCorrectWorkers",
  "WorkerConfs": {
    "one": {
      "WorkerTypeName": "Bam.Net.Automation.Tests.JobManagerUnitTests+TestWorker, bam.net.automation.core.tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "StepNumber": 0,
      "Name": "one",
      "Properties": {
        "RequiredProperties": "[]"
      }
    },
    "two": {
      "WorkerTypeName": "Bam.Net.Automation.Tests.JobManagerUnitTests+TestWorker, bam.net.automation.core.tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "StepNumber": 1,
      "Name": "two",
      "Properties": {
        "RequiredProperties": "[]"
      }
    }
  },
  "WorkerFiles": [
    "/Users/bapellanes/src/BamFrameworkCore/Bam.Net/_tests/core/bam.net.automation.core.tests/TestData/JobManagerService_AfterAddWorkerCreateJobShouldHaveCorrectWorkers/Job_AfterAddWorkerCreateJobShouldHaveCorrectWorkers/one.yaml",
    "/Users/bapellanes/src/BamFrameworkCore/Bam.Net/_tests/core/bam.net.automation.core.tests/TestData/JobManagerService_AfterAddWorkerCreateJobShouldHaveCorrectWorkers/Job_AfterAddWorkerCreateJobShouldHaveCorrectWorkers/two.yaml"
  ],
  "JobDirectory": "/Users/bapellanes/src/BamFrameworkCore/Bam.Net/_tests/core/bam.net.automation.core.tests/TestData/JobManagerService_AfterAddWorkerCreateJobShouldHaveCorrectWorkers/Job_AfterAddWorkerCreateJobShouldHaveCorrectWorkers"
}