SystemDotRuntimePath: C:\Users\bryan.THREEHEADZ\.bam\bin\System.Runtime.dll
NetStandardPath: C:\Users\bryan.THREEHEADZ\.bam\bin\netstandard.dll
SysHomeDir: C:\Users\bryan.THREEHEADZ\.bam
SysDir: C:\bam\src\BamFrameworkCore\Bam.Net\_tools.core\bamdb\.bam
ProcessHomeDir: C:\Users\bryan.THREEHEADZ
