{
  "Name": "Job_eukr",
  "WorkerConfs": {
    "worker": {
      "WorkerTypeName": "Bam.Net.Automation.Tests.JobManagerUnitTests+TestWorker, bam.net.automation.core.tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "StepNumber": 0,
      "Name": "worker",
      "Properties": {
        "RequiredProperties": "[]"
      }
    }
  },
  "WorkerFiles": [
    "/Users/bapellanes/src/BamFrameworkCore/Bam.Net/_tests/core/bam.net.automation.core.tests/TestData/JobManagerService_AddWorkerShouldCreateJob/Job_eukr/worker.yaml"
  ],
  "JobDirectory": "/Users/bapellanes/src/BamFrameworkCore/Bam.Net/_tests/core/bam.net.automation.core.tests/TestData/JobManagerService_AddWorkerShouldCreateJob/Job_eukr"
}