ReferenceAssembliesDir: C:\Users\bryan.THREEHEADZ\.bam\bin\ReferenceAssemblies
GenDir: C:\Users\bryan.THREEHEADZ\.bam\bin\gen
BamHomeDir: C:\Users\bryan.THREEHEADZ\.bam
BamDir: C:\bam\src\BamFrameworkCore\Bam.Net\_tests\core\bam.net.services.core.tests\.bam
ProcessHomeDir: C:\Users\bryan.THREEHEADZ
