{
  "Name": "JobShouldRunIfRunnerThreadIsRunning",
  "WorkerConfs": {
    "19b10565-8ec7-40d1-a229-b457bceb4740": {
      "WorkerTypeName": "Bam.Net.Automation.Tests.JobManagerUnitTests+TestWorker, bam.net.automation.core.tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "StepNumber": 0,
      "Name": "19b10565-8ec7-40d1-a229-b457bceb4740",
      "Properties": {
        "RequiredProperties": "[]"
      }
    }
  },
  "WorkerFiles": [
    "/Users/bapellanes/src/BamFrameworkCore/Bam.Net/_tests/core/bam.net.automation.core.tests/TestData/JobManagerService_JobShouldRunIfRunnerThreadIsRunning/JobShouldRunIfRunnerThreadIsRunning/19b10565-8ec7-40d1-a229-b457bceb4740.yaml"
  ],
  "JobDirectory": "/Users/bapellanes/src/BamFrameworkCore/Bam.Net/_tests/core/bam.net.automation.core.tests/TestData/JobManagerService_JobShouldRunIfRunnerThreadIsRunning/JobShouldRunIfRunnerThreadIsRunning"
}