//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Bam.Net.Automation {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Project {
        
        private ProjectPropertyGroup[] propertyGroupField;
        
        private ProjectItemGroup[] itemGroupField;
        
        private string sdkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PropertyGroup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectPropertyGroup[] PropertyGroup {
            get {
                return this.propertyGroupField;
            }
            set {
                this.propertyGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemGroup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroup[] ItemGroup {
            get {
                return this.itemGroupField;
            }
            set {
                this.itemGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sdk {
            get {
                return this.sdkField;
            }
            set {
                this.sdkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectPropertyGroup {
        
        private string outputTypeField;
        
        private string targetFrameworkField;
        
        private string rootNamespaceField;
        
        private string applicationIconField;
        
        private string packageIdField;
        
        private string versionField;
        
        private string authorsField;
        
        private string companyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OutputType {
            get {
                return this.outputTypeField;
            }
            set {
                this.outputTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TargetFramework {
            get {
                return this.targetFrameworkField;
            }
            set {
                this.targetFrameworkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RootNamespace {
            get {
                return this.rootNamespaceField;
            }
            set {
                this.rootNamespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApplicationIcon {
            get {
                return this.applicationIconField;
            }
            set {
                this.applicationIconField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PackageId {
            get {
                return this.packageIdField;
            }
            set {
                this.packageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Authors {
            get {
                return this.authorsField;
            }
            set {
                this.authorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroup {
        
        private ProjectItemGroupContent[] contentField;
        
        private ProjectItemGroupDeployManifest[] deployManifestField;
        
        private ProjectItemGroupApplicationManifest[] applicationManifestField;
        
        private ProjectItemGroup_DeploymentManifestEntryPoint[] _DeploymentManifestEntryPointField;
        
        private ProjectItemGroup_DebugSymbolsIntermediatePath[] _DebugSymbolsIntermediatePathField;
        
        private ProjectItemGroupIntermediateAssembly[] intermediateAssemblyField;
        
        private ProjectItemGroup_ResolveComReferenceCache[] _ResolveComReferenceCacheField;
        
        private ProjectItemGroup_UnmanagedRegistrationCache[] _UnmanagedRegistrationCacheField;
        
        private ProjectItemGroupProjectReference[] projectReferenceField;
        
        private ProjectItemGroupPackageReference[] packageReferenceField;
        
        private ProjectItemGroupNone[] noneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Content", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroupContent[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeployManifest", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroupDeployManifest[] DeployManifest {
            get {
                return this.deployManifestField;
            }
            set {
                this.deployManifestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ApplicationManifest", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroupApplicationManifest[] ApplicationManifest {
            get {
                return this.applicationManifestField;
            }
            set {
                this.applicationManifestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_DeploymentManifestEntryPoint", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroup_DeploymentManifestEntryPoint[] _DeploymentManifestEntryPoint {
            get {
                return this._DeploymentManifestEntryPointField;
            }
            set {
                this._DeploymentManifestEntryPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_DebugSymbolsIntermediatePath", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroup_DebugSymbolsIntermediatePath[] _DebugSymbolsIntermediatePath {
            get {
                return this._DebugSymbolsIntermediatePathField;
            }
            set {
                this._DebugSymbolsIntermediatePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IntermediateAssembly", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroupIntermediateAssembly[] IntermediateAssembly {
            get {
                return this.intermediateAssemblyField;
            }
            set {
                this.intermediateAssemblyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_ResolveComReferenceCache", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroup_ResolveComReferenceCache[] _ResolveComReferenceCache {
            get {
                return this._ResolveComReferenceCacheField;
            }
            set {
                this._ResolveComReferenceCacheField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_UnmanagedRegistrationCache", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroup_UnmanagedRegistrationCache[] _UnmanagedRegistrationCache {
            get {
                return this._UnmanagedRegistrationCacheField;
            }
            set {
                this._UnmanagedRegistrationCacheField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProjectReference", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroupProjectReference[] ProjectReference {
            get {
                return this.projectReferenceField;
            }
            set {
                this.projectReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PackageReference", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroupPackageReference[] PackageReference {
            get {
                return this.packageReferenceField;
            }
            set {
                this.packageReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("None", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroupNone[] None {
            get {
                return this.noneField;
            }
            set {
                this.noneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroupContent {
        
        private string includeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroupDeployManifest {
        
        private string removeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remove {
            get {
                return this.removeField;
            }
            set {
                this.removeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroupApplicationManifest {
        
        private string removeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remove {
            get {
                return this.removeField;
            }
            set {
                this.removeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroup_DeploymentManifestEntryPoint {
        
        private string removeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remove {
            get {
                return this.removeField;
            }
            set {
                this.removeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroup_DebugSymbolsIntermediatePath {
        
        private string removeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remove {
            get {
                return this.removeField;
            }
            set {
                this.removeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroupIntermediateAssembly {
        
        private string removeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remove {
            get {
                return this.removeField;
            }
            set {
                this.removeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroup_ResolveComReferenceCache {
        
        private string removeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remove {
            get {
                return this.removeField;
            }
            set {
                this.removeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroup_UnmanagedRegistrationCache {
        
        private string removeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remove {
            get {
                return this.removeField;
            }
            set {
                this.removeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroupProjectReference {
        
        private string includeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroupPackageReference {
        
        private string includeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroupNone {
        
        private string copyToOutputDirectoryField;
        
        private string updateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CopyToOutputDirectory {
            get {
                return this.copyToOutputDirectoryField;
            }
            set {
                this.copyToOutputDirectoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NewDataSet {
        
        private Project[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Project")]
        public Project[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
