"$schema": http://json-schema.org/draft-04/schema#
id: application_v1.yaml

title: Blue Cross Blue Shield of Minnesota 2018
javaType: "com.vimly.entitystore.schema.application.ApplicationEntity"
type: object
"@type": "Application"
extends:
    "$ref": "entity_v1.yaml"

additionalProperties: false

properties:
    friendlyId:
      type: string
      example: "AUD-03454-123"
      description: "Friendly Id (System Generated, do not include on POST requests)"
      readOnly: true
    quoteName:
      type: string
      example: "Win-back quote for ABC Corp"
      description: "Information about a quote indicating what is included in the quote"
    customQuoteMessage:
      type: string
      example: "Thanks for considering us, ACME Corporation, for your benefits needs."
      description: "Custom Message to include in quote proposal"
    applicationType:
        "$ref": "#/definitions/types/applicationTypes"
    effectiveDateTime:
      type: string
      format: "date-time"
    baseApplicationId:
      type: string
      description: "Base Application Entity ID when this application is superseding or extending one.  IE, the quote id that this applicaiton was generated based on"
      format: uuid
    effectiveTimeZone:
        "$ref": "common_v1.yaml#/definitions/TimeZone"
    status:
        "$ref": "#/definitions/types/status"
    isAgentAttested:
      type: boolean
    companyProfile:
        "$ref": "#/definitions/forms/companyProfile"
    employerQuestionnaire:
        "$ref": "#/definitions/forms/employerQuestionnaire"
    MSPACA:
        "$ref": "#/definitions/forms/MSPACA"
    proposalDetail:
        "$ref": "#/definitions/types/proposalDetail"
    products:
        type: array
        items:
          "$ref": "#/definitions/types/coverageProductType"
    coverageTypes:
       "$ref": "#/definitions/types/coverageTypes"
    coverages:
        "$ref": "#/definitions/types/coverages"
        
    producerOfRecord:
        "$ref": "#/definitions/forms/producerOfRecord"
    comments:
        "$ref": "#/definitions/forms/comments"
    signatures:
        "$ref": "#/definitions/forms/signatures"
    contacts:
        type: array
        items:
          "$ref": "contact_v1.yaml"
    attachments:
        type: array
        items:
          "$ref": "attachment_v1.yaml"
    validationMessages:
        "$ref": "#/definitions/validation/validationMessages"

required:
    - companyProfile
    - employerQuestionnaire
    - MSPACA
    - plans
    - producerOfRecord
    - comments
    - signatures

definitions:
    types:
        proposalDetail:
          type: object
          properties:
            totalQuotedRate:
              type: number
            previousYear:
              type: integer
              description: "Prior quoting year"
            renewingYear:
              type: integer
              description: "Prior quoting year"

            previousCoverages:
              "$ref": "#/definitions/types/coverages"
            renewingCoverages:
              "$ref": "#/definitions/types/coverages"
            alternativeCoverages:
              "$ref": "#/definitions/types/coverages"

            crosswalks:
              type: array
              items:
                "$ref": "#/definitions/forms/coverageCrosswalk"
        coverageProductType:
          javaType: "com.vimly.entitystore.schema.coverage.CoverageProductType"
          type: string
          enum:
            - MEDICAL
            - DENTAL
            - VISION
      #JED-1513
        coverageTypes:
           type: object
           properties:
              medical:
                type: boolean
                default: false
              vision:
                type: boolean
                default: false
              dental:
                type: boolean
                default: false
        #JED-1513
        coverages:
          type: array
          items:
            "$ref": "#/definitions/types/coverage"

        coverage:
          javaType: "com.vimly.entitystore.schema.coverage.Coverage"
          additionalProperties: false
          type: object
          properties:
            product:
              "$ref": "#/definitions/types/coverageProductType"
            preferredOrder:
              type: number
            serviceProvider:
              type: string
            status:
              type: string
              enum:
                - ACTIVE
                - EXPIRED
                - PROPOSED
                - RENEWING_PROPOSED
            planId:
              type: string
            productId:
              type: string
            groupNumber:
              type: string
            effectiveDate:
              type: string
              format: "date-time"
            contractLengthMonths:
              type: number
            endDate:
              type: string
              format: "date-time"
            source:
              type: string
              enum:
                - CROSSWALK
                - CHOICE

        applicationTypes:
          javaType: "com.vimly.entitystore.schema.application.ApplicationTypeEnum"
          type: string
          enum:
            - QUOTE
            - NEW
            - RENEWAL_AS_IS
            # JED-645 Add new statuses
            - QUOTE_RENEWAL_WITH_CHANGE
            - QUOTE_MIDYEAR_CHANGE
            - QUOTE_SEGMENT_CHANGE
            - APPLICATION_RENEWAL_WITH_CHANGE
            - APPLICATION_MIDYEAR_CHANGE
            - APPLICATION_SEGMENT_CHANGE
            - APPLICATION_RENEWAL_PLAN_ONLY_CHANGE
            - SEGMENT_CHANGE_PLAN_CHANGE_ONLY
            - SEGMENT_CHANGE_FULL_ALTERNATE_RENEWAL
        status:
          javaType: "com.vimly.entitystore.schema.application.ApplicationStatusEnum"
          type: string
          enum:
            - QUOTE_DRAFT
            - QUOTE_QUOTE_GENERATED
            - QUOTE_REJECTED
            - QUOTE_ARCHIVED
            - QUOTE_ACCEPTED
            - APPLICATION_APP_IN_PROGRESS
            - APPLICATION_SUBMITTED_IN_REVIEW
            - APPLICATION_APP_MISSING_INFO
            - APPLICATION_APP_DENIED
            - APPLICATION_NEEDS_SIGNATURE
            - APPLICATION_SOLD_IN_REVIEW
            - APPLICATION_SOLD_FINAL
            - APPLICATION_SOLD_FINAL_PENDING_INSTALL
            - APPLICATION_ARCHIVED
            - RENEWAL_GENERATED
            - RENEWAL_ACCEPTED
            - RENEWAL_RENEWAL_IN_REVIEW
            - RENEWAL_RENEWAL_ON_HOLD
            - RENEWAL_READY
            - RENEWAL_REJECTED
            - RENEWAL_SOLD
            - RENEWAL_SOLD_PENDING_INSTALL
            - RENEWAL_GENERATED_REVIEW_HOLD
            - RENEWAL_VOID
            - UW_EDIT
            - RENEWAL_GENERATING
            
        employerInformation:
            javaType: "com.vimly.entitystore.schema.application.EmployerInformationEntity"
            type: object
            additionalProperties: false
            properties:
                natureOfBusiness:
                    type: string
                    faker: lorem.words
                yearsInBusiness:
                    type: number
                    minimum: 0
                    maximum: 200

            required:
                - contractSigner
                - natureOfBusiness
                - yearsInBusiness

        employeeCountForClass:
            javaType: "com.vimly.entitystore.schema.application.EmployeeCountForClassEntity"
            type: "object"
            properties:
                active:
                    "$ref": "#/definitions/types/employeeCountForProduct"
                cobra:
                    "$ref": "#/definitions/types/employeeCountForProduct"
                other:
                    "$ref": "#/definitions/types/employeeCountForProduct"
            required:
                - active
                - cobra
                - other

        employeeCountForProduct:
            type: "object"
            properties:
                medical:
                    type: integer
                    minimum: 0
                dental:
                    type: integer
                    minimum: 0
                vision:
                    type: integer
                    minimum: 0
            required:
                - medical
                - dental
                - vision

        contributionAmount:
            javaType: "com.vimly.entitystore.schema.application.ContributionAmount"
            type: object
            additionalProperties: false
            properties:
                "employeePercentage":
                    type: number
                    minimum: 0
                    maximum: 100
                    faker:
                        "finance.amount": [0,100,1]
                "dependentPercentage":
                    type: number
                    minimum: 0
                    maximum: 100
                    faker:
                        "finance.amount": [0,100,1]
                "employeeFixedAmount":
                    type: number
                    minimum: 0
                    faker:
                        "finance.amount": [0,1000,2]
                "dependentFixedAmount":
                    type: number
                    minimum: 0
                    faker:
                        "finance.amount": [0,1000,2]
            #required:
            #    - employeePercentage
            #    - dependentPercentage
            #    - employeeFixedAmount

                        #    - dependentFixedAmount

        eligibilitySpecification:
            javaType: "com.vimly.entitystore.schema.application.EligiblitySpecification"
            type: object
            additionalProperties: false
            properties:
                hoursPerWeekForEligibility:
                    type: number
                    minimum: 0
                eligibleToEnrollTimeframe:
                    type: string
                    enum:
                      - HIRE_DATE # HireDate
                      - NEXT_DAY_30_DAYS # NextDay_30Days
                      - NEXT_DAY_60_DAYS # NextDay_60Days
                      - NEXT_DAY_90_DAYS # NextDay_90Days
                      - FIRST_DAY_MONTH_HIRE_DATE # FirstDayMonth_HireDate
                      - FIRST_DAY_MONTH_30_DAYS # FirstDayMonth_30Days
                      - FIRST_DAY_MONTH_60_DAYS # FirstDayMonth_60Days
                      #["HireDate", "NextDay_30Days", "NextDay_60Days", "NextDay_90Days", "FirstDayMonth_HireDate", "FirstDayMonth_30Days", "FirstDayMonth_60Days"]
                eligibleToEnrollComments:
                    type: string
                    faker: lorem.paragraph

        companyApplicationInformation:
            javaType: "com.vimly.entitystore.schema.application.CompanyApplicationInformationEntity"
            type: object
            additionalProperties: false
            required:
                - primaryCompany
                - legalName
                - taxId
                - address
                - isCoverDomesticPartners
            properties:
                company:
                    "$ref": "company_v1.yaml"


                ################### Questions ###
                isCoverDomesticPartners:
                    type: boolean

                # aponsorship and Ownership
                planSponsorship:
                    "$ref": "common_v1.yaml#/definitions/PlanSponsorship"

                # Union Information
                isEmployeesCoveredByUnion:
                    type: boolean
                producerSignature:
                    "$ref": "digitalsignature_v1.yaml"
                isIRS414Aggregate:
                    type: boolean

                isApplyingForCoverage:
                    type: boolean

                # Contributions
                contributions:
                    javaType: "com.vimly.entitystore.schema.application.ContributionEntity"
                    type: object
                    additionalProperties: false
                    properties:
                        employerMedical:
                            "$ref": "#/definitions/types/contributionAmount"
                        employerDental:
                            "$ref": "#/definitions/types/contributionAmount"
                        employerVision:
                            "$ref": "#/definitions/types/contributionAmount"

                # Contributions
                eligibility:
                    javaType: "com.vimly.entitystore.schema.application.Eligibility"
                    type: object
                    additionalProperties: false
                    properties:
                        default:
                            "$ref": "#/definitions/types/eligibilitySpecification"
                        medical:
                            "$ref": "#/definitions/types/eligibilitySpecification"
                        dental:
                            "$ref": "#/definitions/types/eligibilitySpecification"
                        vision:
                            "$ref": "#/definitions/types/eligibilitySpecification"

                # Plan Subscriptions
                coverages:
                    "$ref": "#/definitions/types/coverages"
                proposalDetail:
                    "$ref": "#/definitions/types/proposalDetail"

    forms:
        companyProfile:
            javaType: "com.vimly.entitystore.schema.application.CompanyProfileEntity"
            type: object
            additionalProperties: false
            properties:
                primaryCompany:
                    "$ref": "#/definitions/types/companyApplicationInformation"
                additionalCompanies:
                    type: array
                    minOccurs: 0
                    maxOccurs: 50
                    items:
                        "$ref": "#/definitions/types/companyApplicationInformation"
                employeeCountForClass:
                    javaType: "com.vimly.entitystore.schema.application.ApplicationEmployeeCountForClass"
                    type: object
                    additionalProperties: false
                    properties:
                        numberEligible:
                            "$ref": "#/definitions/types/employeeCountForClass"
                        numberEnrolling:
                            "$ref": "#/definitions/types/employeeCountForClass"
                        numberWaving:
                            "$ref": "#/definitions/types/employeeCountForClass"
                    required:
                        - numberEligible
                        - numberEnrolling
                        - numberWaving
            required:
                - primaryCompany
                - employeeCountForClass

        employerQuestionnaire:
            javaType: "com.vimly.entitystore.schema.application.EmployerQuestionnaireEntity"
            type: object
            additionalProperties: false
            properties:
                isHqInMN:
                    _comment: Is Headquarts in MN?
                    type: "boolean"
                hqAddress:
                    _comment: If HQ is not in MN, then get the address
                    "$ref": "address_v1.yaml"

                hasContractEmployees:
                    type: boolean
                contractEmployeeNameList:
                    type: array
                    items:
                        type: object
                        additionalProperties: false
                        properties:
                          firstName:
                              type: string
                              faker: name.firstName
                          middleName:
                              type: string
                              faker: name.middleName
                          lastName:
                              type: string
                              faker: name.lastName
                hasCurrentGroupMedical:
                    type: boolean
                currentGroupMedicalProvider:
                    type: string
                checkboxNoCostSharingAssistance:
                  type: boolean
                bcbsnbHasIchra:
                    type: boolean
                bcbsmnEmployeeClasses:
                  type: string


        MSPACA:
            javaType: "com.vimly.entitystore.schema.application.MSPACAEntity"
            type: object
            additionalProperties: false
            properties:
                mspEmployeeCount:
                    type: string
                    enum:
                        ["1-19", "20-99", "100+"]
                acaMarketEmployeeCount:
                    type: integer
                    mininum: 0
            required:
                - mspEmployeeCount
                - acaMarketEmployeeCount

        coverageCrosswalk:
            javaType: "com.vimly.entitystore.schema.application.CoverageCrosswalk"
            type: object
            additionalProperties: false
            properties:
                previousCoverage:
                    "$ref": "#/definitions/types/coverage"
                newCoverage:
                    "$ref": "#/definitions/types/coverage"
            required:
                - previousCoverage
                - newCoverage

        producerOfRecord:
            javaType: "com.vimly.entitystore.schema.application.ProducerOfRecordEntity"
            type: object
            additionalProperties: false
            properties:
                agencyName:
                    type: string
                    faker: company.companyName
                agencyNumber:
                    type: string
                producerName:
                    type: string
                    faker: company.companyName
                producerNumber:
                    type: string
                producerPhone:
                    type: string
                    faker: phone.phoneNumber
                producerEmailAddress:
                    type: string
                    faker: internet.email
                producerSignature:
                    "$ref": "digitalsignature_v1.yaml"
                salesRepresentative:
                    "$ref": "contact_v1.yaml"

        comments:
            javaType: "com.vimly.entitystore.schema.application.CommentEntity"
            type: object
            additionalProperties: false
            properties:
                comments:
                    type: string
                    faker: lorem.paragraph

        signatures:
            javaType: "com.vimly.entitystore.schema.application.SignatureEntity"
            type: object
            additionalProperties: false
            properties:
                representativeName:
                    type: string
                    faker: name.findName
                representativeTitle:
                    type: string
                    faker: name.jobTitle
                representativeSignature:
                    "$ref": "digitalsignature_v1.yaml"
                representativeSignedDate:
                    type: string
                    format: "date-time"

    validation:
        validationMessages:
            type: array
            items:
                javaType: "com.vimly.entitystore.schema.application.ValidationMessage"
                type: object
                additionalProperties: false
                properties:
                    messageType:
                        type: string
                        enum:
                        - ERROR
                        - UNDERWRITING_FLAG
                    sourceEntity:
                        type: string
                    sourceProperty:
                        type: string
                    errorCode:
                        type: integer
                    ruleCode:
                        type: string
                    ruleName:
                        type: string
                    message:
                        type: string
