name: Build Lib, Tools & Tests

on: 
  push:
    branches:
      - bam-net-core-dev

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DIST: /tmp/bam
    steps:
    - uses: actions/checkout@v1
    - name: Build 
      run: ./build-all.sh
    - uses: actions/upload-artifact@v1
      with:
        name: DIST
        path: /tmp/bam
