name: Build Lib, Tools & Tests

on: 
  push:
    branches:
      - bam-net-core-dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      DIST: /tmp/bam
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.CI_PAT }}
        submodules: true
    - name: Build
      run: ./build.sh
    - name: Upload Toolkit
      uses: actions/upload-artifact@v1
      with:
        name: BamToolkit
        path: /tmp/bam/bamtoolkit.zip
    - name: Upload Tests
      uses: actions/upload-artifact@v1
      with:
        name: BamToolkit-Tests
        path: /tmp/bam/tests/bamtoolkit-tests.zip
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Tests
        uses: actions/download-artifact@v1
        with:
          name: BamToolkit-Tests
