name: Build Lib & Tools

on: 
  push:
    branches:
      - bam-net-core-dev

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DIST: /tmp/bam
    steps:
    - uses: actions/checkout@v1
    - name: Build 
      run: ./build-dev.sh
