name: Build Lib, Tools & Tests

on: 
  push:
    branches:
      - bam-net-core-dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      DIST: /opt/bam/dist
      CI_USERNAME: "ci"
      CI_EMAIL: "ci@threeheadz.com"
      COMMIT_TO_BRANCH: "bam-net-core-test"
      GIT_COMMIT_MESSAGE: "committed by github action (bam-net-core-dev)"
      GIT_COMMIT_AUTHOR: "ci <ci@threeheadz.com>"
      GIT_ADD_FILE_PATTERN: "."
      GIT_COMMIT_OPTIONS: ""
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.CI_ACCESSTOKEN }}
        submodules: true
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100' 
    - name: Build
      run: ./build.sh
    - name: Upload Tests
      uses: actions/upload-artifact@v2
      with:      
        name: "BamToolkit-Tests-${{ github.sha }}"
        path: /opt/bam/tests
    - name: Upload BamToolkit
      uses: actions/upload-artifact@v2
      with:
        name: BamToolkit-${{ github.sha }}
        path: /opt/bam/artifacts
    - name: Commit Test Branch
      run: ./push-test.sh
